
/*
 This file was autogenerated via
 -------------------------------
 ldetool generate branch.lde
 -------------------------------
 do not touch it with bare hands!
*/

package main

import (
	"bytes"
)

var starSpace = []byte("* ")

// Branch ...
type Branch struct {
	Rest []byte
	Head struct {
		Valid bool
	}
	Name string
}

// Extract ...
func (p *Branch) Extract(line []byte) (bool, error) {
	p.Rest = line
	var rest1 []byte
	rest1 = p.Rest

	// Checks if the rest starts with `"* "` and pass it
	if bytes.HasPrefix(rest1, starSpace) {
		rest1 = rest1[len(starSpace):]
	} else {
		p.Head.Valid = false
		goto branchHeadLabel
	}
	p.Head.Valid = true
	p.Rest = rest1
branchHeadLabel:

	// Take the rest as Name(str)
	p.Name = string(p.Rest)
	p.Rest = p.Rest[len(p.Rest):]
	return true, nil
}
