// Code generated by ldetool generate --go-string filters.lde. DO NOT EDIT.

package main

import (
	"strings"
)

var constAces = "aces"
var constBslashesGjagentDotExe = "\\gjagent.exe"
var constGtaMinusVcDotExe = "gta-vc.exe"
var constLauncher = "launcher"
var constSlashShadowOfMordorSlash = "/ShadowOfMordor/"
var constWarSpaceThunder = "War Thunder"
var constWitcher3DotExe = "witcher3.exe"
var constWitcherDotExe = "witcher.exe"

// WarThunderAces ...
type WarThunderAces struct {
	Rest string
}

// Extract ...
func (p *WarThunderAces) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "aces" and then pass it
	pos = strings.Index(p.Rest, constAces)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constAces):]
	} else {
		return false, nil
	}

	// Check if the rest is empty
	if len(p.Rest) != 0 {
		return false, nil
	}

	return true, nil
}

// WarThunderLauncher ...
type WarThunderLauncher struct {
	Rest string
}

// Extract ...
func (p *WarThunderLauncher) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "War Thunder" and then pass it
	pos = strings.Index(p.Rest, constWarSpaceThunder)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constWarSpaceThunder):]
	} else {
		return false, nil
	}

	// Looking for "launcher" and then pass it
	pos = strings.Index(p.Rest, constLauncher)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constLauncher):]
	} else {
		return false, nil
	}

	return true, nil
}

// GajinAgent ...
type GajinAgent struct {
	Rest string
}

// Extract ...
func (p *GajinAgent) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "\\gjagent.exe" and then pass it
	pos = strings.Index(p.Rest, constBslashesGjagentDotExe)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constBslashesGjagentDotExe):]
	} else {
		return false, nil
	}

	// Check if the rest is empty
	if len(p.Rest) != 0 {
		return false, nil
	}

	return true, nil
}

// Witcher3 ...
type Witcher3 struct {
	Rest string
}

// Extract ...
func (p *Witcher3) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "witcher3.exe" and then pass it
	pos = strings.Index(p.Rest, constWitcher3DotExe)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constWitcher3DotExe):]
	} else {
		return false, nil
	}

	// Check if the rest is empty
	if len(p.Rest) != 0 {
		return false, nil
	}

	return true, nil
}

// TheWitcher ...
type TheWitcher struct {
	Rest string
}

// Extract ...
func (p *TheWitcher) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "witcher.exe" and then pass it
	pos = strings.Index(p.Rest, constWitcherDotExe)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constWitcherDotExe):]
	} else {
		return false, nil
	}

	// Check if the rest is empty
	if len(p.Rest) != 0 {
		return false, nil
	}

	return true, nil
}

// GTAViceCity ...
type GTAViceCity struct {
	Rest string
}

// Extract ...
func (p *GTAViceCity) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "gta-vc.exe" and then pass it
	pos = strings.Index(p.Rest, constGtaMinusVcDotExe)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constGtaMinusVcDotExe):]
	} else {
		return false, nil
	}

	// Check if the rest is empty
	if len(p.Rest) != 0 {
		return false, nil
	}

	return true, nil
}

// ShadowOfMordor ...
type ShadowOfMordor struct {
	Rest string
}

// Extract ...
func (p *ShadowOfMordor) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Looking for "/ShadowOfMordor/" and then pass it
	pos = strings.Index(p.Rest, constSlashShadowOfMordorSlash)
	if pos >= 0 {
		p.Rest = p.Rest[pos+len(constSlashShadowOfMordorSlash):]
	} else {
		return false, nil
	}

	return true, nil
}
