// Code generated by fenneg version v0.0.0-20260331211044-6ef5929cd8c6+dirty. DO NOT EDIT.

package metadata

import (
	"encoding/binary"

	"github.com/sirkon/errors"
	"github.com/sirkon/varsize"
)

const (
	dumpCodeDeleted = 1
)

// Deleted encodes arguments tuple of this method.
func (w *DumpLogger) Deleted(name string, description string, data []byte) []byte {
	lenName := varsize.Uint(uint(len(name))) + len(name)
	lenDescription := varsize.Uint(uint(len(description))) + len(description)
	lenData := varsize.Len(data) + len(data)
	var buf []byte
	{
		bufSize := 4 + lenName + lenDescription + lenData
		buf = w.allocateBuffer(varsize.Uint(uint64(bufSize)) + bufSize)

		// Encode record length.
		buf = binary.AppendUvarint(buf, uint64(bufSize))
	}

	// Encode branch (method) code.
	buf = binary.LittleEndian.AppendUint32(buf, uint32(dumpCodeDeleted))

	// Encode name(string).
	buf = binary.AppendUvarint(buf, uint64(len(name)))
	buf = append(buf, name...)

	// Encode description(string).
	buf = binary.AppendUvarint(buf, uint64(len(description)))
	buf = append(buf, description...)

	// Encode data([]byte).
	buf = binary.AppendUvarint(buf, uint64(len(data)))
	buf = append(buf, data...)

	return buf
}

// DumpLoggerDispatch dispatches encoded data made with DumpLogger
func DumpLoggerDispatch(disp Dump, rec []byte) error {
	if len(rec) < 4 {
		return errors.New("decode branch code: record buffer is too small").Uint64("length-required", uint64(4)).Int("length-actual", len(rec))
	}

	branch := binary.LittleEndian.Uint32(rec[:4])
	rec = rec[4:]

	switch branch {
	case dumpCodeDeleted:
		// Decode name(string).
		var name string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Deleted.name(string) length: record buffer is too small")
				}
				return errors.New("decode Deleted.name(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Deleted.name(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			name = string(rec[:size])
			rec = rec[size:]
		}

		// Decode description(string).
		var description string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Deleted.description(string) length: record buffer is too small")
				}
				return errors.New("decode Deleted.description(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Deleted.description(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			description = string(rec[:size])
			rec = rec[size:]
		}

		// Decode data([]byte).
		var data []byte
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Deleted.data([]byte) length: record buffer is too small")
				}
				return errors.New("decode Deleted.data([]byte) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if uint64(len(rec)) < size {
				return errors.New("decode Deleted.data([]byte) content: record buffer is too small").Uint64("length-required", uint64(size)).Int("length-actual", len(rec))
			}
			data = rec[:size]
			rec = rec[size:]
		}

		if len(rec) > 0 {
			return errors.New("decode Deleted: the record was not emptied after the last argument decoded").Int("record-bytes-left", len(rec))
		}

		if err := disp.Deleted(name, description, data); err != nil {
			return errors.Wrap(err, "call Deleted")
		}

		return nil

	default:
		return errors.Newf("invalid branch code %d", branch).Uint32("invalid-branch-code", branch)
	}

	return nil
}
