// Code generated by fenneg version v0.0.0-20260331211044-6ef5929cd8c6+dirty. DO NOT EDIT.

package metadata

import (
	"encoding/binary"

	"github.com/sirkon/errors"
	"github.com/sirkon/varsize"
)

const (
	operationsCodeAdd = 1
	operationsCodeDel = 2
)

// Add encodes arguments tuple of this method.
func (w *OperationsLogger) Add(name string, description string, path string) []byte {
	lenName := varsize.Uint(uint(len(name))) + len(name)
	lenDescription := varsize.Uint(uint(len(description))) + len(description)
	lenPath := varsize.Uint(uint(len(path))) + len(path)
	var buf []byte
	{
		bufSize := 4 + lenName + lenDescription + lenPath
		buf = w.allocateBuffer(varsize.Uint(uint64(bufSize)) + bufSize)

		// Encode record length.
		buf = binary.AppendUvarint(buf, uint64(bufSize))
	}

	// Encode branch (method) code.
	buf = binary.LittleEndian.AppendUint32(buf, uint32(operationsCodeAdd))

	// Encode name(string).
	buf = binary.AppendUvarint(buf, uint64(len(name)))
	buf = append(buf, name...)

	// Encode description(string).
	buf = binary.AppendUvarint(buf, uint64(len(description)))
	buf = append(buf, description...)

	// Encode path(string).
	buf = binary.AppendUvarint(buf, uint64(len(path)))
	buf = append(buf, path...)

	return buf
}

// Del encodes arguments tuple of this method.
func (w *OperationsLogger) Del(name string) []byte {
	lenName := varsize.Uint(uint(len(name))) + len(name)
	var buf []byte
	{
		bufSize := 4 + lenName
		buf = w.allocateBuffer(varsize.Uint(uint64(bufSize)) + bufSize)

		// Encode record length.
		buf = binary.AppendUvarint(buf, uint64(bufSize))
	}

	// Encode branch (method) code.
	buf = binary.LittleEndian.AppendUint32(buf, uint32(operationsCodeDel))

	// Encode name(string).
	buf = binary.AppendUvarint(buf, uint64(len(name)))
	buf = append(buf, name...)

	return buf
}

// OperationsLoggerDispatch dispatches encoded data made with OperationsLogger
func OperationsLoggerDispatch(disp Operations, rec []byte) error {
	if len(rec) < 4 {
		return errors.New("decode branch code: record buffer is too small").Uint64("length-required", uint64(4)).Int("length-actual", len(rec))
	}

	branch := binary.LittleEndian.Uint32(rec[:4])
	rec = rec[4:]

	switch branch {
	case operationsCodeAdd:
		// Decode name(string).
		var name string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Add.name(string) length: record buffer is too small")
				}
				return errors.New("decode Add.name(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Add.name(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			name = string(rec[:size])
			rec = rec[size:]
		}

		// Decode description(string).
		var description string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Add.description(string) length: record buffer is too small")
				}
				return errors.New("decode Add.description(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Add.description(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			description = string(rec[:size])
			rec = rec[size:]
		}

		// Decode path(string).
		var path string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Add.path(string) length: record buffer is too small")
				}
				return errors.New("decode Add.path(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Add.path(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			path = string(rec[:size])
			rec = rec[size:]
		}

		if len(rec) > 0 {
			return errors.New("decode Add: the record was not emptied after the last argument decoded").Int("record-bytes-left", len(rec))
		}

		if err := disp.Add(name, description, path); err != nil {
			return errors.Wrap(err, "call Add")
		}

		return nil

	case operationsCodeDel:
		// Decode name(string).
		var name string
		{
			size, off := binary.Uvarint(rec)
			if off <= 0 {
				if off == 0 {
					return errors.New("decode Del.name(string) length: record buffer is too small")
				}
				return errors.New("decode Del.name(string) length: malformed uvarint sequence")
			}
			rec = rec[off:]
			if int(size) > len(rec) {
				return errors.New("decode Del.name(string) content: record buffer is too small").Uint64("length-required", uint64(int(size))).Int("length-actual", len(rec))
			}
			name = string(rec[:size])
			rec = rec[size:]
		}

		if len(rec) > 0 {
			return errors.New("decode Del: the record was not emptied after the last argument decoded").Int("record-bytes-left", len(rec))
		}

		if err := disp.Del(name); err != nil {
			return errors.Wrap(err, "call Del")
		}

		return nil

	default:
		return errors.Newf("invalid branch code %d", branch).Uint32("invalid-branch-code", branch)
	}

	return nil
}
