
/*
 This file was autogenerated via
 -------------------------------
 ldetool generate texting.lde
 -------------------------------
 do not touch it with bare hands!
*/

package main

import (
	"bytes"
)

var starSpace = []byte("* ")

// Branch ...
type Branch struct {
	Rest    []byte
	Current struct {
		Valid bool
	}
	Branch string
}

// Extract ...
func (p *Branch) Extract(line []byte) (bool, error) {
	p.Rest = line
	var rest1 []byte
	rest1 = p.Rest

	// Checks if the rest starts with `"* "` and pass it
	if bytes.HasPrefix(rest1, starSpace) {
		rest1 = rest1[len(starSpace):]
	} else {
		p.Current.Valid = false
		goto branchCurrentLabel
	}
	p.Current.Valid = true
	p.Rest = rest1
branchCurrentLabel:

	// Take the rest as Branch(str)
	p.Branch = string(p.Rest)
	p.Rest = p.Rest[len(p.Rest):]
	return true, nil
}
